### ISSUE TITLE
AirSimNH release version

### ISSUE THREAD

**Issue by evbtst** [ValentinaZangirolami/DRL#1]
Hi!
Nice code!! =)

Which version of the AirSimNH release did you use?

I'm using 1.7.0, but in the middle of training I have an error:

LogExit: Executing StaticShutdownAfterError
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)

Can you help me?

Thanks in advance!

**Comment by evbtst** [comment]
Error log:

CommonUnixCrashHandler: Signal=11
[2022.05.10-13.27.34:034][726]LogCore: === Critical error: ===
Unhandled Exception: SIGSEGV: unaligned memory access (SIMD vectors?)

[2022.05.10-13.27.34:034][726]LogCore: Fatal error!

0x0000000002d7483f AirSimNH!UE4Function_Private::TFunctionRefCaller<WorldSimApi::getObjectPose(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const::$_55, void ()>::Call(void*) [/datadrive/ue_425/ue-4.25.1-linux-debugeditor/Engine/Source/Runtime/Core/Public/Templates/Function.h:548]
0x0000000002ce93c1 AirSimNH!TGraphTask<FFunctionGraphTask>::ExecuteTask(TArray<FBaseGraphTask*, TSizedDefaultAllocator<32> >&, ENamedThreads::Type) [/datadrive/ue_425/ue-4.25.1-linux-debugeditor/Engine/Source/Runtime/Core/Public/Async/TaskGraphInterfaces.h:849]
0x00000000036fccf2 AirSimNH!FNamedTaskThread::ProcessTasksNamedThread(int, bool)()
0x00000000036fc004 AirSimNH!FNamedTaskThread::ProcessTasksUntilIdle(int)()
0x00000000036f9ce4 AirSimNH!FTaskGraphImplementation::ProcessThreadUntilIdle(ENamedThreads::Type)()
0x0000000006bc94e0 AirSimNH!FTickTaskSequencer::ReleaseTickGroup(ETickingGroup, bool)()
0x0000000006bc4e6b AirSimNH!FTickTaskManager::RunTickGroup(ETickingGroup, bool)()
0x00000000065b283d AirSimNH!UWorld::Tick(ELevelTick, float)()
0x000000000642a830 AirSimNH!UGameEngine::Tick(float, bool)()
0x0000000002c6e821 AirSimNH!FEngineLoop::Tick()()
0x0000000002c755da AirSimNH!GuardedMain(char16_t const*)()
0x000000000752c5ab AirSimNH!CommonUnixMain(int, char**, int (*)(char16_t const*), void (*)())()
0x00007f36cf13fc87 libc.so.6!__libc_start_main(+0xe6)
0x0000000002c69029 AirSimNH!_start()

[2022.05.10-13.27.34:090][726]LogExit: Executing StaticShutdownAfterError
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)

**Comment by ValentinaZangirolami** [comment]
Hi,
Try to set neighbourhood=False in AirsimEnv.py (_animals_out).

If this solution doesn't work, you should try another releases. I used v1.5.0

Thank you
