### ISSUE TITLE
Could paraters in AirSim setting like "ClockSpeed" effect training results?

### ISSUE THREAD

**Issue by iseecow** [ValentinaZangirolami/DRL#3]
Hi！
An attractive project and easy to run. 
I have some inquiries I'd like to discuss. I try to run the source code with only MBE equels to true, the evaluation score only reaches to 38.23 after capturing 860,089 frames. 
May this due to my AirSim setting, in which I set "ClockSpeed" = 30? And is there anything else I should notice in AirSim setting? 
I`m also tring to run the code with both MBE and VDBE equal to true, while ClockSpeed = 1. Could model after 1 milion of frames reaches to the similar outcome like showing video? Additionally, could you provide some trained models or parameter files?
Best Wishes

**Comment by ValentinaZangirolami** [comment]
> ClockSpeed

Hi! 

Happy to hear that you are easy running this code. I never tried to change the ClockSpeed, but I found an open issue about it (here https://github.com/microsoft/AirSim/issues/4841 ). They said that changing the ClockSpeed brings some consequences on the physics of AirSim. If the physics changes, I think it may also affect the reproducibility of my results.

Write me an email (valentina.zangirolami@gmail.com) for trained models, parameter or/and airsim setting files. After that, I will provide them as soon as possible.

Thank you,
Best Regards

**Comment by iseecow** [comment]
Thank you for your notice
I`ve sent the email. By the way, I'm curious whether the training effect of the model will be improved when NUM_ACTIONS=9 in the code? Actually, I think it may be not very reasonable for the steering value to be +-0.5 in the five action spaces when making a small turn, which seems too large.
Yours sincerely.

**Comment by ValentinaZangirolami** [comment]
> Thank you for your notice I`ve sent the email. 

I will reply asap.


> By the way, I'm curious whether the training effect of the model will be improved when NUM_ACTIONS=9 in the code? Actually, I think it may be not very reasonable for the steering value to be +-0.5 in the five action spaces when making a small turn, which seems too large. Yours sincerely.

We tried to increase the number of actions since 5 actions may be (as you supposed) not enough to better control the steering. Basically, we enhance the granularity of actions just to test if our model can obtain the same (good) performance. Still using the same hyperparameter of the case NUM_ACTIONS=5, we obtained similar performance, slightly worse, but basically the result is really closed to the video in the README.

Best

**Comment by iseecow** [comment]
Thank you for your help with my questions. Your explanations were clear and really appreciated.
Best regards
